<?php

namespace DashboardBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    /*
     * @return Notification[]
     */
    public function getLast($limit){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT n FROM DashboardBundle:Notification n ORDER BY n.id DESC'
            )
            ->setMaxResults($limit)->getResult();
    }
}
