<?php

namespace DashboardBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAssigned(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM DashboardBundle:Service s WHERE s.server IS NOT NULL'
            )
            ->getResult();
    }
}
